[project]
name = "mavlink"
description = "Tools for swingby's avionics system"
readme = "README.md"
authors = [
    { name = "Yuta Suzuki", email = "suzuki7yuta@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []
dynamic = ["version"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[dependency-groups]
dev = [
    "pymavlink>=2.4.49",
    "pyserial>=3.5",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]
